name: Sanity Test
on: [push]
jobs:
  automated_test:
    name: Sanity Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: crunch the numbers
      run: python find_lowest_number.py numbers.txt lowest_number.txt
    - name: Compare expected output to actual. please tell me this works
      run: diff lowest_number.txt lettherebelight.txt
