name: Sanity Test
on: [push]
jobs:
  automated_test:
    name: Sanity Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Produce sanity check
      run: python idiotcheck.py > test.txt
    - name: Compare expected output to actual
      run: diff test.txt idiot_text.txt
